### ISSUE TITLE
Add unit tests for Post components

### ISSUE THREAD

**Issue by forrestwilkins** [praxis-app/praxis#16]
We need to add unit tests for all Post components.

Please refer to the the [Adding Unit Tests section](https://github.com/forrestwilkins/praxis/blob/main/CONTRIBUTING.md#adding-unit-tests) of our `CONTRIBUTING.md` and feel free to use [`Header.test.tsx`](https://github.com/forrestwilkins/praxis/blob/main/src/components/_App/__tests__/Header.test.tsx) as reference.

**Comment by averyfairbanks** [comment]
Currently being working on in: [implement-post-tests branch](/forrestwilkins/praxis/tree/implement-post-tests)

**Comment by forrestwilkins** [comment]
The UI portion of the project has been moved to another repo: https://github.com/praxis-project/praxis-ui
