### ISSUE TITLE
Investigate potential memory leak - Backend

### ISSUE THREAD

**Issue by averyfairbanks** [praxis-app/praxis#23]
Upon first liking a post, the console throws this error:
> `(node:11148) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:11148) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

Investigate what is causing this and if it could cause problems in the future

**Comment by forrestwilkins** [comment]
There's a similar issue occurring on the client side: #26

**Comment by forrestwilkins** [comment]
This error seems to eventually culminate as the following `JavaScript heap out of memory` error: https://pastebin.com/raw/ef910wEV

Adding the following and removing all instances of circular importing apparently resolves the issue (https://github.com/vercel/next.js/issues/15855#issuecomment-707773781):
```
{
  "scripts": {
    "start": "NODE_OPTIONS=--max_old_space_size=8192 next"
  }
}
```

**Comment by forrestwilkins** [comment]
This has turned out to be a non-issue and can be resolved by merely restarting the development server. This does not occur in production and is a result of a combination between circular dependencies and hot reloading during development.
https://github.com/vercel/next.js/issues/15855

**Comment by forrestwilkins** [comment]
This issue could potentially be resolved by updating to Next.js version 11: https://github.com/vercel/next.js/issues/15855

**Comment by forrestwilkins** [comment]
The backend is no longer using Next.js or Prisma.
