### ISSUE TITLE
Implement Cascading Deletes

### ISSUE THREAD

**Issue by forrestwilkins** [praxis-app/praxis#25]
Prisma doesn't currently support [cascading deletes](https://www.prisma.io/docs/guides/database/advanced-database-tasks/cascading-deletes) out of the box. When a user is deleted, their posts should automatically be deleted as well, without us having to delete them manually in the resolver. A current workaround seems to be available with [@paljs/plugins](https://paljs.com/plugins/delete/).

**Comment by averyfairbanks** [comment]
https://www.prisma.io/docs/guides/database/advanced-database-tasks/cascading-deletes/postgresql

**Comment by averyfairbanks** [comment]
First implementation of cascading deletes for User-Post relationship. Images associate with the deleted user are deleted off local storage as well. Further investigation is needed for each relationship upon deletion, to determine which current resolvers can be removed.
