### ISSUE TITLE
Cascading deletes not handling Like, Comment, Image entries

### ISSUE THREAD

**Issue by averyfairbanks** [praxis-app/praxis#49]
When User is deleted, every record associated with them is correctly deleted from the database using cascading deletes, except likes on posts. These are currently handled within the deletePost mutation in the post resolver.

See: lines 155-158 in apollo/resolvers/post

It would make sense to unify or method for deleting entries associated with deleted users. We want the cascading deletes to handle this as it should.

EDIT: Its possible that additional relationships may need to be added between models to handle this condition.

**Comment by averyfairbanks** [comment]
It appears that in addition to Like entries, Comment and Image entries are not being properly removed by cascading deletes. I still believe additional relationships in the Prisma Schema could handle this. Perhaps we use new relationships as an intermediary between models that are not directly linked but still need deletion upon their indirect relations deletion.

**Comment by forrestwilkins** [comment]
This was an issue specific to Prisma and the API is now using TypeORM.
